version: '3.5'
services:
  frontend:
    build: .
    container_name: frontend_cams_viewer
    restart: on-failure
    command: "npm run build"
    working_dir: /app
    volumes:
         - /home/viktoria:/app/dist
